spring:
  datasource:
    url: jdbc:sqlserver://sahilmanhas.database.windows.net:1433;database=sahilsinghdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sahildb
    password: SahilManhas068@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


